### ISSUE TITLE
Suggestion: Move the menu item to the Window menu

### ISSUE THREAD

**Issue by owlboy** [Varneon/UdonExplorer#5]
Hello!

I'd like to make a suggestion that the Verneon menu be moved to the Window menu. A lot of assets choose to live in the main menu bar, and it really is taking up a lot of space. And in my opinion, the more polite practice is to put your menu under  Window. 

I think this is something all assets targeting VRChat should do. That way there is room for everyone, without stuffing the main menu bar.

And yes, I recognize this may be more applicable on macOS. 😅

Thank you for considering!

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/237349/211977709-96c02624-3ed3-4633-8427-b01f1c05f2c9.png">

**Comment by Varneon** [comment]
Hi,

Thank you for the suggestion.

The decision to preserve the "Varneon" toolbar menu item was made after over the last couple years several hundred menu items from several different packages started accumulating under my name, and most often if someone is using one of my products, they are using more than one, thus the top-level menu item making them easier to access.

For developers using only a handful of my products in their projects at a time this may indeed be seen as a questionable decision, thus thanks to your suggestion, I've decided to solve this with the following:

You can now add a [Scripting Define Symbol](https://docs.unity3d.com/Manual/CustomScriptingSymbols.html) called `VARNEON_HIDE_TOOLBAR_MENU`, this will move the menu item of Udon Explorer from `Varneon/Udon Explorer` to `Window/Varneon/Udon Explorer`:

![image](https://user-images.githubusercontent.com/26690821/211986456-f31773fd-e856-437e-be08-8332d590981d.png)

This feature will be available in 0.3.4 when it goes live.

-Varneon

**Comment by Varneon** [comment]
Udon Explorer 0.3.4 is now available for download here: https://github.com/Varneon/UdonExplorer/releases/tag/0.3.4

**Comment by owlboy** [comment]
Thank you!
